#!/usr/bin/env python
"""
Simple test runner script for preprocessing functions.
Run this script to execute all unit tests.
This file was generated by GitHub Copilot.
"""

import sys
import os
import unittest

# Add the current directory to Python path so we can import preprocessing
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

if __name__ == '__main__':
    # Discover and run all tests
    loader = unittest.TestLoader()
    start_dir = '.'
    suite = loader.discover(start_dir, pattern='test_*.py')
    
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    # Exit with error code if tests failed
    sys.exit(not result.wasSuccessful())